site_name: Alium for React
repo_url: https://github.com/example/repository/

#nav:
#  - default: Getting Started/intro.md

theme:
  name: material
  logo: logo.png
  favicon: logo.png
  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.instant
#    - header.autohide
    - navigation.tracking
#    - navigation.tabs
#    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top

  palette:
    - scheme: default
      primary: teal
      accent: yellow
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      primary: teal
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
